### ISSUE TITLE
Process doesn't close when closing main window

### ISSUE THREAD

**Issue by DaanMeijer** [OpenSAGE/OpenSAGE#366] opened 2020-01-07 08:45 UTC
When I run OpenSage.Launcher, and close the window by using the little x, the process in my terminal still runs.

**Comment by feliwir** [comment] 2020-01-22 07:42
That's not the case for me neither on Windows or on Linux. The terminal is staying open, but that's the default VS /  VSCode behaviour

**Comment by feliwir** [comment] 2022-01-04 16:00
Closing since i can't reproduce this

**Closed by feliwir** 2022-01-04 16:00 UTC
Labels: invalid
