### ISSUE TITLE
Generals ZH remaster version

### ISSUE THREAD

**Issue by DetroyT** [OpenSAGE/OpenSAGE#30] opened 2018-01-02 13:27 UTC
I have a question. I see that there is an active work on this game engine and I believe in the next 2 years you will be able to finish your work. In this regard: can I start the parallel work on preparing a remaster version?
The creation of 3d models and textures also takes some time, and considering the forthcoming amount of work (civil models and fractions models), I think that it will take as much time as work on the game engine.

The future system requirements are also interesting.
How much RAM do I need to count? Can I use high poly models (20000-40000), normal maps, specular maps?

P/s
Now I'm busy porting the generals to the C&C 3 engine, I've overcome many difficulties (even implemented the dozer), but thanks to your work, I can switch my attention to the remaster version.

**Comment by tgjones** [comment] 2018-01-02 14:34
Hi @DetroyT!

> I believe in the next 2 years you will be able to finish your work

I think that's over-optimistic :) It depends on how many people help out, but I'm expecting it to take 5 years minimum, and probably more, to fully re-implement Generals. So far we've only really done the file format parsing, and after that there's the whole game, which is far more complicated than parsing file formats.

> How much RAM do I need to count? Can I use high poly models (20000-40000), normal maps, specular maps?

I don't yet know the answers to those questions. OpenSAGE's renderer is still evolving. When it's done, I'd expect it to perform quite well in comparison to the original C&C games.

> Now I'm busy porting the generals to the C&C 3 engine, I've overcome many difficulties (even implemented the dozer), but thanks to your work, I can switch my attention to the remaster version.

That sounds like an interesting project! I've wondered myself what Generals would look like with a newer underlying engine, which is obviously part of the motivation for OpenSAGE. But OpenSAGE is still at such an early stage that I'd be cautious about recommending you building something on top of it - there's just too much left to do.

**Comment by DetroyT** [comment] 2018-01-02 15:04
I'm sure that these 5 years will fly by quickly.
As long as the game engine is not ready, I will use CnC3 and BFME II to represent models in the game (with shaders, normal maps and other visual effects).
When you finish your work, I will  to move the new models to the original game.

**Comment by ZexaronS** [comment] 2018-01-02 16:58
@DetroyT What do you think about the logic/behavior/balance it self to be considered in the remaster. I have started some thinking about this and did some wiki posts on Thyme's project,  however as there's multiple projects to improve GenZH now, I think it's better to spin off those efforts and make it so that each project can choose whether it includes them or not, or that the users decide manually on their own which things they will put together, however, the problem is because some of the logic needs core changes such as bug fixes and that can't be done only in ini.

So I think that the documentation part would be in the separate project, as in some kind of a spec/standard and then these projects would try to implement it as accurately as possible.

**Comment by feliwir** [comment] 2018-01-02 21:45
Please note that any balance/gameplay changes are not the scope of OpenSage. These changes don’t require a new engine, which is the purpose of this project. You can change gameplay/balance related factors through the builtin INI system.

**Comment by DetroyT** [comment] 2018-01-03 15:38
I think OpenSage should become a platform for creating games in the genre of real-time strategy (like a Unity 3d engine). And the first draft will be this is a remaster version of the original game without changing the in-game balance (only graphic improvements).

**Comment by penev92** [comment] 2018-01-03 17:47
It may eventually become that, or more, but @tgjones has a more realistic expectation on the time it takes.
Since I have been wondering how to contact you folks for a few days now but didn't want to spam any important issues or PRs, I'll just use this opportunity. I wanted to ask if there is any way to contact you, like IRC, Discord, Skype, or at least a forum, since GitHub issues are hardly the place. :)

**Comment by feliwir** [comment] 2018-01-03 19:17
@DetroyT this project is going to stay SAGE related. Of course you can make any modifications to the game files as you already could in the original game (but with a superiour engine hopefully).

@penev92 Tim and I are currently doing all chatting in skype, but we are planning to setup a Gitter/Discord/Slack Channel (we are not sure yet) in the near future so we can communincate with non-developers in an better way.

**Comment by DetroyT** [comment] 2018-01-03 19:42
>  Of course you can make any modifications to the game files as you already could in the original game (but with a superiour engine hopefully).

With shaders, post effects, normal maps, bump terrains,  special clouds, weather and fog effects, right ?
And all this without restrictions on the use of resources of RAM, processor and video adapter.

**Comment by feliwir** [comment] 2018-01-03 20:34
@DetroyT it's not time to think about any additional features until the base game is working. Doing visual enhancements to the base game can be worked on afterwards (and we'll have that optionally). Also I don't think that those are **necessary** features, but more a nice to have thing.
But as i mentioned before the focus right now is to reimplementing the games with their original assets.
And we do know that BFME2 and introduced normal mapping into the SAGE engine, but thanks for the hint anyways 👍

**Comment by tgjones** [comment] 2018-01-04 10:27
>  So I think that the documentation part would be in the separate project, as in some kind of a spec/standard and then these projects would try to implement it as accurately as possible.

@ZexaronS We have https://github.com/OpenSAGE/Docs for exactly that purpose - to provide a place for SAGE docs that is (slightly) separate from the OpenSAGE code repo.

**Comment by tgjones** [comment] 2018-01-04 10:29
> I wanted to ask if there is any way to contact you, like IRC, Discord, Skype, or at least a forum, since GitHub issues are hardly the place. :)

@penev92 We have a shiny new Discord server - here's the [invite link](https://discord.gg/BXzyFb). I'll add that to the readme soon.

**Comment by tgjones** [comment] 2018-01-04 10:31
Closing this because I think all the questions that can be answered at this stage, have been answered. We won't know system requirements or anything of that nature for a long time yet.

Anyway, I'm very glad to hear that there is [at least the potential of] interest from the modding community in this project :)

**Closed by tgjones** 2018-01-04 10:31 UTC
